language: objective-c
before_install:
  - gem install cocoapods -v 1.3.1
osx_image: xcode9.3
branches:
  only:
  - master
env:
  global:
  - WORKSPACE="HelloMixpanel/HelloMixpanel.xcworkspace"
  - SCHEME="[iOS] HelloMixpanel"
  matrix:
    - DESTINATION="OS=10.0,name=iPhone 7" RUN_TESTS="YES" POD_LINT="YES"
    - DESTINATION="OS=11.1,name=iPhone X" RUN_TESTS="YES" POD_LINT="NO"
podfile: HelloMixpanel/podfile
script:
- set -o pipefail
- xcodebuild -version
- xcodebuild -showsdks

# travis_retry here because sometimes tests mysteriously fail without running any tests but will succeed the next time
- travis_retry xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c
- xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO build | xcpretty -c

# Run `pod lib lint` if specified
# allow warnings while surveys are deprecated but not yet removed. disallow them again later
- if [ $POD_LINT == "YES" ]; then
    pod lib lint --allow-warnings;
  fi
